### ISSUE TITLE
Adding Datasets

### ISSUE THREAD

**Issue by amrapalijz** [slrbl/human-in-the-loop-machine-learning-tool-tornado#2]
After I logged in, I clicked on "Add dataset". I used the CSV file from https://www.kaggle.com/fabdelja/autism-screening-for-toddlers/version/1.

1. I get this error "Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for "127.0.0.1" port 9200)": https://drive.google.com/open?id=1mX5rUT5iEv3LnzhPvKFqlNG0uaJbGPWM.

2. When I click back I do see a list of the same dataset and the multiple attempts to upload: https://drive.google.com/open?id=1P6TAKUcXUh9UBG4tuf5dxWQ_HR_OSvZU. 

3. When I click on one of those datasets, I get an error "Something went wrong..", see https://drive.google.com/open?id=1lbyflIit6MA4lHuBh-Zq_FYtRYbTyjT5.

**Comment by slrbl** [comment]
It looks like an Elasticsearch problem. Could you check if it is running ? you can use the following command:
`ps -eaf | grep elastic`

**Comment by amrapalijz** [comment]
It shows:

Amrapalis-MBP:tornado-active-learning amrapaliz$ ps -eaf | grep elastic
  501 85987  2099   0  2:17PM ttys002    0:00.01 grep elastic

**Comment by slrbl** [comment]
That means it's not running. 
Could try: 
```
cd ./tornado_data/elasticsearch-6.2.4/
./bin/elasticsearch
```

**Comment by amrapalijz** [comment]
Did and then it gives me this error

`Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-02-26T19:55:57,563][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: plugins directory [/AMaastricht/1Projects/1Crowdsourcing/8OptimAL/tornado-active-learning/tornado_data/elasticsearch-6.2.4/plugins] not found
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.4.jar:6.2.4]
Caused by: java.lang.IllegalStateException: plugins directory [/AMaastricht/1Projects/1Crowdsourcing/8OptimAL/tornado-active-learning/tornado_data/elasticsearch-6.2.4/plugins] not found
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:67) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 6 more`

**Comment by slrbl** [comment]
So, it's an ES problem. Could you download ES and replace the one in ./tornado_data/elasticsearch-6.2.4/ with it ? You will need rename it with "elasticsearch-6.2.4".

**Comment by amrapalijz** [comment]
ok I was getting an error with elasticsearch (https://github.com/elastic/elasticsearch/issues/35218) but managed to install it with brew (https://gist.github.com/jpalala/ab3c33dd9ee5a6efbdae) and then replaced the ./tornado_data/elasticsearch-6.2.4/ folder and renamed it. Now when I added the kaggle dataset I am now able to see the dataset table.

**Comment by slrbl** [comment]
Could you clone another Tornado and make this modification in the new folder and try again ?

**Comment by amrapalijz** [comment]
I cloned another Tornado and made the same modifications (sqlite and elasticsearch) but I get an error: https://drive.google.com/file/d/1mX5rUT5iEv3LnzhPvKFqlNG0uaJbGPWM/view?usp=sharing when I am trying to upload the CSV file and create the dataset.

**Comment by slrbl** [comment]
Could you share the CSV Dataset you are using ?

**Comment by amrapalijz** [comment]
Im using the one in your example https://www.kaggle.com/fabdelja/autism-screening-for-toddlers

**Comment by slrbl** [comment]
It's again an ES problem, you need to make sure it's running and listening on https://127.0.0.1:9200.
